#!/bin/bash

cp .gitconfig .tmux.conf .vimrc .zshrc ~

mkdir ~/.vim/backup/ ~/.vim/undo/ ~/.vim/swap/
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

sudo apt-get --ignore-missing install vim tmux zsh fonts-powerline
